#define THRUSTER_AZIMUTH_CONTROL 0.0
#define THRUSTER_MAXIMUM_MOTOR_TEMPERATURE_RATING 373.0
#define THRUSTER_MAXIMUM_ROTATIONAL_SPEED 2000
#define THRUSTER_MOTOR_CURRENT 0
#define THRUSTER_MOTOR_POWER_RATING 8000
#define THRUSTER_MOTOR_TEMPERATURE 0
#define THRUSTER_MOTOR_TYPE 4
#define THRUSTER_SPEED_CONTROL 100
