#define DEVICE_INDUSTRY_GROUP 4
#define DEVICE_MANUFACTURER_CODE 2046
#define DEVICE_UNIQUE_NUMBER 2898
#define PRODUCT_CERTIFICATION_LEVEL 1
#define PRODUCT_FIRMWARE_VERSION "1.0.0"
#define PRODUCT_LEN 3
#define PRODUCT_N2K_VERSION 2101
#define PRODUCT_VERSION "1.0"
