#define DEVICE_CLASS 25
#define DEVICE_FUNCTION 130
#define DEVICE_INDUSTRY_GROUP 4
#define DEVICE_MANUFACTURER_CODE 2046
#define DEVICE_UNIQUE_NUMBER 2114
#define GPIO_LED_BOARD 13
#define GPIO_LED_DOWN 9
#define GPIO_LED_PWR 7
#define GPIO_LED_UP 8
#define GPIO_PINS_INPUT { GPIO_SENSOR_DPD, GPIO_SENSOR_DPG, GPIO_SENSOR_OVL, GPIO_SENSOR_ROT, GPIO_SENSOR_RTD, GPIO_SENSOR_RTG, GPIO_SWITCH_ENABLE, GPIO_SWITCH_INSTANCE0, GPIO_SWITCH_INSTANCE1, GPIO_SWITCH_INSTANCE2, GPIO_SWITCH_INSTANCE3, GPIO_SWITCH_INSTANCE4, GPIO_SWITCH_INSTANCE5, GPIO_SWITCH_INSTANCE6 }
#define GPIO_PINS_INSTANCE { GPIO_SWITCH_INSTANCE0, GPIO_SWITCH_INSTANCE1, GPIO_SWITCH_INSTANCE2, GPIO_SWITCH_INSTANCE3, GPIO_SWITCH_INSTANCE4, GPIO_SWITCH_INSTANCE5, GPIO_SWITCH_INSTANCE6 }
#define GPIO_PINS_OUTPUT { GPIO_RELAY_DOWN, GPIO_RELAY_UP, GPIO_LED_BOARD, GPIO_LED_DOWN, GPIO_LED_PWR, GPIO_LED_UP }
#define GPIO_RELAY_DOWN 6
#define GPIO_RELAY_UP 5
#define GPIO_SENSOR_DPD 21
#define GPIO_SENSOR_DPG 1
#define GPIO_SENSOR_OVL 2
#define GPIO_SENSOR_ROT 23
#define GPIO_SENSOR_RTD 22
#define GPIO_SENSOR_RTG 0
#define GPIO_SWITCH_ENABLE 12
#define GPIO_SWITCH_INSTANCE0 14
#define GPIO_SWITCH_INSTANCE1 15
#define GPIO_SWITCH_INSTANCE2 16
#define GPIO_SWITCH_INSTANCE3 17
#define GPIO_SWITCH_INSTANCE4 18
#define GPIO_SWITCH_INSTANCE5 19
#define GPIO_SWITCH_INSTANCE6 20
#define PRODUCT_CERTIFICATION_LEVEL 1
#define PRODUCT_CODE 1
#define PRODUCT_FIRMWARE_VERSION "1.0"
#define PRODUCT_LEN 3
#define PRODUCT_N2K_VERSION 2101
#define PRODUCT_SERIAL_CODE "429"
#define PRODUCT_TYPE "MODINT"
#define PRODUCT_VERSION "1.0"
