#!/bin/bash
#
# usage: get-config-values [dirname...]

declare -a OUTPUT
OUTPUT=()

if [ "${1}" == "" ] ; then
   	${0} "."
else
	STARTDIR="$(pwd)"
	while [ "${1}" != "" ] ; do
		cd "${STARTDIR}"
		if [ -d "${1}" ] ; then
			cd "$(readlink -f ${1})"
  			while :; do
    				for rname in * ; do
      					if [[ ( -f "${rname}" ) && ( "${rname}" == "${rname^^}" ) && ( "${rname}" == *"_"* ) ]] ; then
						NAME=${rname%++}
      						VALUE=$(cat "${rname}");
      						OUTPUT+=("${NAME} ${VALUE}")

						# Increment the value of files whose name ends in ++
      						if [[ "${rname}" == *"++" ]] ; then echo "$((VALUE + 1))" > ${rname} ; fi
      					fi
    				done
    				if [ "$(basename `pwd`)" == "ankreo" ] ; then break ; fi
    				cd ..
  			done
		fi
		shift
	done
	printf '%s\n' "${OUTPUT[@]}" | sort | uniq
fi
