#!/bin/bash

TARGET=${1}

if [ -f "${TARGET}" ] ; then
	while IFS='$\n' read -r line; do
   		key=${line%% *}
    		key="${key#"${key%%[![:space:]]*}"}"
    		key="${key%"${key##*[![:space:]]}"}"   
   		value=${line#* }
    		value="${value#"${value%%[![:space:]]*}"}"
    		value="${value%"${value##*[![:space:]]}"}"   
		sed -i "/${key}.*=/ s!=.*;!= ${value};!" ${TARGET}
		#sed -i "/^#define ${key}\s+/ s!^.*$!#define ${key} ${value}!" ${TARGET}
	done
fi

